name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup demo
        run: |
          mkdir test3
          touch test3/oof.txt
          touch test3/.dot.txt
      - name: Copy with user/pw
        uses: sangbumwoo/atlantis-server@master
        with:
          local: test3/oof.txt
          remote: scp/user/pw/oof.txt
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}        
